### ISSUE TITLE
打包的exe一闪而过

### ISSUE THREAD

**Issue by iljfsdi** [Lz1y/FreeForWenku#1]

**Comment by renqiang06** [comment]
我研究了一下，不是直接运行exe
需要文档网址，保存类型这两个参数。
我测试正确运行方式可以是：
1.cmd指定到该exe所在目录
2.输入：FreeForWenku https://wenku.baidu.com/view/09f3e7c9a1c7aa00b52acb96.html?from=search  ppt
3.回车，结果会保存在当前目录
